### ISSUE TITLE
Iteration 1 Analysis Report feedback

### ISSUE THREAD

**Issue by ugurdogrusoz** [selimfirat/1D.man-of-war#4]
Please see me asap!

**Comment by ugurdogrusoz** [comment]
FR: OK
NFR: OK
UC: Missing (no UC descriptions!)
Object: ?
Dynamic: Missing
UI: Missing
Note: Poor formatting (no title page, no ToC!)

**Comment by cerenuysal** [comment]
The meeting has already done.
